name: main

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'
  release:
    types: [published]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - run: pip cache dir
      - run: pip cache list
      - run: pip cache info
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit clean
          pre-commit autoupdate
          pre-commit run --all-files
  pdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - run: pip cache dir
      - run: pip cache list
      - run: pip cache info
      - uses: mpi4py/setup-mpi@v1
      - name: Build
        run: |
          pip install pdoc3
          pip install -e .
          pip cache dir
          pip cache list
          pip cache info
          python -We -m pdoc --html PySuperDropletLES
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          BRANCH: pdoc
          FOLDER: html/PySuperDropletLES
          CLEAN: true

  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mpi4py/setup-mpi@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - run: pip cache dir
      - run: pip cache list
      - run: pip cache info
      - name: Install dependencies
        run: |
#          python -m pip install --upgrade pip
          pip install -e .
          pip cache dir
          pip cache list
          pip cache info
          pip install pylint pytest

      - name: Analysing the code with pylint
        run: |
          pylint --unsafe-load-any-extension=y $(git ls-files '*.py')

  build:
    needs: [pylint, pdoc, precommit]
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - run: pip cache dir
      - run: pip cache list
      - run: pip cache info
      - uses: mpi4py/setup-mpi@v1
      - run: pip install -e .
      - run: | 
          pip cache dir
          pip cache list
          pip cache info
      - run: python -We -c "import PySuperDropletLES"
      - run: pip install pytest
      - run: mpiexec -n 2 pytest -p no:unraisableexception -We

  dist:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # https://github.com/pypa/setuptools_scm/issues/480
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - run: pip cache dir
      - run: pip cache list
      - run: pip cache info
      - run: pip install twine build
      - run: |
          unset CI
          python -m build 2>&1 | tee build.log
          exit `fgrep -i warning build.log | wc -l`
      - run: twine check --strict dist/*
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@unstable/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@unstable/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
